# jwt.secret-key=${JWT_SECRET_KEY}
# hashing.secret-key=${HASHING_SECRET_KEY}

# # Frontend redirect url
# frontend.oauth2.redirect-url=${FRONTEND_OAUTH2_REDIRECT_URL}

jwt.secret-key=0At8mPeL2GSB0wHEsC0xL76Vlw4s5cvzU5puKfmcbLJruWmtmmUq4TtLqfAh9+1+
hashing.secret-key=TOiIHFAHZVYlzWmUd3P0yBWw+s+CwZt4eOaYDoqlXDPruatA+B0ltnm8+C3KY+Fu

# Frontend redirect url
frontend.oauth2.redirect-url=http://localhost:3000/verifying/oauth2-success