services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HASHING_SECERT_KEY=TOiIHFAHZVYlzWmUd3P0yBWw+s+CwZt4eOaYDoqlXDPruatA+B0ltnm8+C3KY+Fu
      - NEXT_PUBLIC_BACKEND_OAUTH2_URL=http://localhost:8989/oauth2/authorization/google
    # Mount volumes for development if needed
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped
    networks:
      - swd-fe-app-network


networks:
  swd-fe-app-network:
    driver: bridge