package swd392.chatbotservice.domain.entity;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import lombok.Data;
import swd392.chatbotservice.infrastructure.utils.ChatItemJsonConverter;
import swd392.chatbotservice.infrastructure.utils.VietnamTimestampConverter;

@Data
@DynamoDBTable(tableName = "swd392_chatbot_service")
public class ChatHistory {
    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "user_id")
    private UUID userId;

    @DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBTypeConverted(converter = VietnamTimestampConverter.class)
    private Instant createdDate = Instant.now();

    @DynamoDBAttribute(attributeName = "histories")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = ChatItemJsonConverter.class)
    private List<ChatItem> histories;

}
