services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - CONFIG_IMPORT_SERVER_URL={YOUR_CONFIG_IMPORT_SERVER_URL} #configserver:http://config-server:8888
    depends_on:
      rabbit-mq:
        condition: service_healthy
    networks:
      - aas-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/v1/configserver/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-gateway-service:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway-service
    container_name: api-gateway-service
    ports:
      - "8222:8222"
    environment:
      - CONFIG_IMPORT_SERVER_URL={YOUR_CONFIG_IMPORT_SERVER_URL}
      - CLASSROOM_SERVICE_URL={YOUR_CLASSROOM_SERVICE_URL}
      - SUBMISSION_SERVICE_URL={YOUR_SUBMISSION_SERVICE_URL}
    depends_on:
      rabbit-mq:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - aas-app-network

#  classroom-service:
#    build:
#      context: ./classroom-service
#      dockerfile: Dockerfile
#    image: classroom-service
#    container_name: classroom-service
#    working_dir: /app
#    environment:
#      - CONFIG_IMPORT_SERVER_URL={YOUR_CONFIG_IMPORT_SERVER_URL}
#      - POSTGRES_DB_URL={YOUR_POSTGRES_DB_URL}
#      - POSTGRES_USER={YOUR_POSTGRES_USER}
#      - POSTGRES_PASSWORD={YOUR_POSTGRES_PASSWORD}
#    depends_on:
#      rabbit-mq:
#        condition: service_healthy
#      config-server:
#        condition: service_healthy
#    networks:
#      - aas-app-network
#
#  submission-service:
#    build:
#      context: ./submission-service
#      dockerfile: Dockerfile
#    image: submission-service
#    container_name: submission-service
#    working_dir: /app
#    environment:
#      - CONFIG_IMPORT_SERVER_URL={YOUR_CONFIG_IMPORT_SERVER_URL}
#      - AWS_REGION={AWS_REGION}
#      - AWS_DYNAMODB_ENDPOINT={AWS_DYNAMODB_ENDPOINT}
#      - AWS_ASSESS_KEY={CREDENTIALS_AWS_ACCESS_KEY}
#      - AWS_SECRET_KEY={CREDENTIALS_AWS_SECRET_KEY}
#    depends_on:
#      rabbit-mq:
#        condition: service_healthy
#      config-server:
#        condition: service_healthy
#    networks:
#      - aas-app-network

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
      - "5672:5672" # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: {YOUR_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: {YOUR_RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - aas-app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

  chatbot-service:
    build:
      context: ./chatbot-service
      dockerfile: Dockerfile
    image: chatbot-service
    container_name: chatbot-service
    ports:
      - "8093:8093"
    environment:
      - GEMINI_API_KEY={gemini.api.key}
    depends_on:
      rabbit-mq:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - aas-app-network

networks:
  aas-app-network:
    driver: bridge

volumes:
  rabbitmq-data: