services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10240:10240"
    volumes:
      - ..:/workspace:cached 
    depends_on:
      - rabbitmq
    command: sleep infinity

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ (AMQP)
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 29112004thuan
