services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
      - "8989:8989"
      - "8080:8080"
      - "8888:8888"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "8096:8096"
    volumes:
      - ..:/workspace:cached 
    depends_on:
      - rabbitmq
    command: sleep infinity

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ (AMQP)
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 29112004thuan

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data: