spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: #allowedOrigins
              - "http://localhost:3000"
              - "http://192.168.2.73:3000"
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: '*'
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8989}
          predicates:
            - Path=/oauth2/authorization/google

        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8989}
          predicates:
            - Path=/api/v1/identity/**

        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8989}
          predicates:
            - Path=/api/v1/admin/**

        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8989}
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, Bearer {accessToken}

        - id: cloud-storage-service
          uri: ${CLOUD_STORAGE_SERVICE_URL:http://localhost:8091}
          predicates:
            - Path=/api/v1/aws/s3/**
        
        - id: law-service
          uri: ${LAW_SERVICE_URL:http://localhost:8092}
          predicates:
            - Path=/api/v1/law/**
        
        - id: chatbot-service
          uri: ${CHATBOT_SERVICE_URL:http://localhost:8093}
          predicates:
            - Path=/api/v1/chatbot/**

        - id: user-package-service
          uri: ${USER_PACKAGE_SERVICE_URL:http://localhost:8094}
          predicates:
            - Path=/api/v1/user-packages/**

  application:
    name: gateway-service

server:
  port: 8222
  address: 0.0.0.0